language: cpp
dist: trusty

git:
  depth: 1


# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

# sourced from https://github.com/tplgy/bonefish/blob/master/.travis.yml

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-6', 'libstdc++-6-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-6', 'libstdc++-6-dev', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-3.8', 'llvm-toolchain-precise-3.8', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=DEBUG

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang-3.8', 'llvm-toolchain-precise-3.8', 'ninja-build', 'cmake', 'xorg-dev', 'libglu1-mesa-dev' ]
      env: CMAKE_BUILD_TYPE=RELEASE

before_install:
  - env
  - export SRC_DIR="`pwd`"
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang-3.8" CC="clang-3.8"; fi

script:
  - $CXX --version
  - cmake --version
  - mkdir "$TRAVIS_BUILD_DIR/build-ninja"
  - cd "$TRAVIS_BUILD_DIR/build-ninja"
  - pwd
  - cmake -Dstdlib=libstdc++ -GNinja "$SRC_DIR"
  - ninja -v
