# Specify version format
version: "{build}"

os:
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

clone_script:
  - cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive

clone_depth: 1

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: git submodule update --init

clone_folder: C:\projects\Dusk

before_build:
  - cmd: cd C:\projects\Dusk
  - cmd: md build
  - cmd: cd build
  - cmd: if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

build:
  project: C:\projects\Dusk\build\Dusk.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off
